server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.98.62:3306/ecourse?zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20