server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://10.0.23.245:38141/test_ecourse?zeroDateTimeBehavior=convertToNull&useSSL=false
    username: yf_user
    password: izFNsI4Fkmynras3V5
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20